ver: 1 # config 版本

webhookURL: "" # webhookURL

webhookeewinfo: | # webhookeewinfo
  {
    "embeds":[{
      "description" : "%Time% 左右發生顯著有感地震\n\n東經: %EastLongitude% 度\n北緯: %NorthLatitude% 度\n位於: %location%\n深度: %Depth% 公里\n規模: %Scale%\n第%Number%報%Final%\nhttps://www.google.com/maps/search/?api=1&query=%NorthLatitude%,%EastLongitude%\n\n發報單位: %Provider%\n\n慎防強烈搖晃，就近避難 [趴下、掩護、穩住]",
      "color"       : 4629503
    }]
  }

ttsnotification: false